### ISSUE TITLE
Text tweaks in PoW section description 

### ISSUE THREAD

**Issue by davecgh** [decred/hardforkdemo#11]
Once the majority of the PoW miners have upgraded (75% of the 100 most recent blocks are at the latest version) and the majority of the PoS miners **have upgraded** (75% of the votes in a 2016 block **interval**), the voting process begins.

The PoW upgrade process uses a rolling window while PoS uses a fixed interval, hence the distinction.

**Comment by alexlyp** [comment]
Fixed in incoming PR
