### ISSUE TITLE
Pop-up dialogs, repeating information (Interaction & Visual Design)

### ISSUE THREAD

**Issue by ta-lind** [decred/hardforkdemo#116]
Can we remove the repeating notifications? I think it could be just the one at the top if its communicating the same information. This will probably need another way of being displayed when we would have agendas that have been restarted or have different waiting period.

<img width="951" alt="screen shot 2017-05-08 at 15 21 13" src="https://cloud.githubusercontent.com/assets/17774057/25806711/cfd08b28-340c-11e7-882f-5fc457fd1117.png">

**Comment by karamble** [comment]
i just want to mention that every agenda got its own "statusbar" because it could be the case, that one agenda allready succeed/failed and the other one will be an upcoming (we are still itterating trough agendas there and this status bar is a part of an agenda) - currently i will not be able to remove it in the second one just with frontent/template variable code

**Comment by ta-lind** [comment]
Ok, the current use of the pop-up notification was intented to communicate the waiting period for all Agendas, thus having it for each isn't really optimal. 

Since the waiting state is temporary, I would say a logical place incorporated into the Agenda Cards would be either under A the "Voting Overview" area or B replacing the "%" bar.
<img width="765" alt="screen shot 2017-05-10 at 13 53 39" src="https://cloud.githubusercontent.com/assets/17774057/25895439/8a2f5a36-3588-11e7-9c6a-2b8b0731c4c4.png">

**Comment by ta-lind** [comment]
I recommend that we should stop using the notification pop-up dialog all together. Its not really optimal to communicate stuff about each agenda there, as they could be integrated inside the Agenda Card instead.  

Also the description area should be kept clear of temporary and additional data. For example the extra and background data could be shown either as hover dialogs in relevant places or grouped below the title where the technical bits live. This assures everything is grouped logically and the cards hierarchy stays intact. 

<img width="1017" alt="screen shot 2017-05-15 at 13 37 27" src="https://cloud.githubusercontent.com/assets/17774057/26054003/ca2fd536-3973-11e7-81d0-9cf0102deff3.png">
