### ISSUE TITLE
Testnet faucet link

### ISSUE THREAD

**Issue by dajohi** [decred/hardforkdemo#27]
If hardforkdemo is running mainnet, should it:

1. Display the testnet faucet link
2. Not display the testnet faucet link
3. Not display but instead include a link to the testnet hardforkdemo website, and vice versa with only the faucet link on the testnet instance.
4. or?

**Comment by jrick** [comment]
2 because 3 may not make any sense if there is no vote taking place on testnet.

**Comment by alexlyp** [comment]
Not display link.  No link to testnet hard demo site.   This would cause more confusion.

**Comment by alexlyp** [comment]
Done
