### ISSUE TITLE
Automatically update site as data changes

### ISSUE THREAD

**Issue by davecgh** [decred/hardforkdemo#77]
The site should ideally automatically update itself every time a new block is received.  This would involve pushing notifications out over websockets which I suspect is too much work to be complete before the initial release.

A reasonable alternative that should be quick to implement would be to update every 5 minutes on `mainnet` and 2 minutes on `testnet` since those are the average block times on both.  This could be done with a simple `setInterval` in the javascript.

**Comment by karamble** [comment]
<meta http-equiv="refresh" content="300" >
Will put a simple Refresh Metatag in Seconds

**Comment by alexlyp** [comment]
Fixed in #80
