### ISSUE TITLE
Change "Reject Threshold" to "Accept Threshold" (or Just Threshold?)

### ISSUE THREAD

**Issue by NickEngland** [decred/hardforkdemo#82]
It's not clear what you are Rejecting with the 95% and 75% Thresholds in the PoW and PoS version upgrade windows.

Are you not Accepting the change if it goes above this value?

It might be clearer as just Threshold: 95%.

**Comment by alexlyp** [comment]
Ah yah, so that is based off of the actual param in dcrd, BlockRejectNumRequired.  We'll try and find a better way to describe it.

**Comment by chappjc** [comment]
I'm suggesting "Upgrade Threshold"

**Comment by alexlyp** [comment]
I like it, I'll make a PR
