### ISSUE TITLE
Intervals are incorrect in the PoS upgrade expand view

### ISSUE THREAD

**Issue by davecgh** [decred/hardforkdemo#94]
The labels for the intervals on the chart improperly overlap.  For example, currently they show:

![image](https://cloud.githubusercontent.com/assets/2115102/25729596/eebe92fa-30fb-11e7-8a26-84f4db6426c7.png)

Notice how the left-most interval says `123040-125056`, and the next one says `125056-127072`.  They should instead be: `123040-125055` and `125056-127071`, etc, since it wouldn't make sense for a block to be in both intervals.

The actual counts themselves also need to be manually checked because I suspect they very well could be incorrect due to the fact the interval labels are incorrect.

**Comment by alexlyp** [comment]
Fixes in recent commit
