### ISSUE TITLE
Rename labels for upgrade sections.

### ISSUE THREAD

**Issue by davecgh** [decred/hardforkdemo#95]
I showed the site to 2 different people that know very little about Decred and one of the immediate observations was that `PoW` and `PoS` are confusing.  It was also not clear that the sections were referring to upgrading.  Both of these can be improved by renaming the labels as follows:

![image](https://cloud.githubusercontent.com/assets/2115102/25730936/04fc9df4-3107-11e7-95c7-1c76c5201307.png)

**Comment by alexlyp** [comment]
Fixed in recent commit
